import {CSSProperties} from '../../jsx-types'

export function setStyles(element: HTMLElement, styles: CSSProperties) {
  for (const style in styles) {
    const value = (styles as any)[style]

    if (typeof value === 'number' && isPixValue(style)) {
      ;(styles as any)[style] = value + 'px'
    } else {
      element.style[style as any] = value
    }
  }
}

function isPixValue(styleName: string): boolean {
  // Generated by co-pilot, so beware.
  switch (styleName) {
    case 'width':
    case 'height':
    case 'top':
    case 'left':
    case 'right':
    case 'bottom':
    case 'fontSize':
    case 'borderWidth':
    case 'borderRadius':
    case 'padding':
    case 'paddingTop':
    case 'paddingLeft':
    case 'paddingRight':
    case 'paddingBottom':
    case 'margin':
    case 'marginTop':
    case 'marginLeft':
    case 'marginRight':
    case 'marginBottom':
    case 'lineHeight':
    case 'letterSpacing':
    case 'strokeWidth':
    case 'outlineWidth':
    case 'outlineOffset':
    case 'strokeDashoffset':
    case 'strokeDasharray':
    case 'borderTopWidth':
    case 'borderLeftWidth':
    case 'borderRightWidth':
    case 'borderBottomWidth':
    case 'borderTopLeftRadius':
    case 'borderTopRightRadius':
    case 'borderBottomLeftRadius':
    case 'borderBottomRightRadius':
      return true
    default:
      return false
  }
}
